services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./mc_servers:/app/mc_servers
      - ./proxy:/shared/proxy:rw
    ports:
      - "8000:8000"
    # Backend container exposes port range for Minecraft servers
    expose:
      - "25565-25600"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - minecraft_network
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "1105:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - minecraft_network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "25565-25600:25565-25600"
      - "8404:8404"
    volumes:
      - ./proxy:/usr/local/etc/haproxy:rw
    networks:
      - minecraft_network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  minecraft_network:
    driver: bridge
