services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./mc_servers:/app/mc_servers
      - ./proxy:/shared/proxy:rw
    ports:
      - "8000:8000"
    # Backend container exposes port range for Minecraft servers
    expose:
      - "25565-25600"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - minecraft_network
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "1105:1105"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - minecraft_network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      # HAProxy Stats Interface (localhost only)
      - "127.0.0.1:8404:8404"
      # Standard Minecraft Java Ports
      - "25565-25600:25565-25600"
      # Minecraft Bedrock Ports
      - "19132-19200:19132-19200"
      # Flexible User Port Ranges
      - "1024-1104:1024-1104"    # User range 1 (excluding 1105)
      - "1106-1199:1106-1199"    # User range 1b (after frontend port)
      - "1200-1399:1200-1399"    # User range 2 (includes 1234, 1106)
      - "3000-3199:3000-3199"    # User range 3
      - "4000-4199:4000-4199"    # User range 4
      - "7000-7199:7000-7199"    # User range 5
      - "9000-9199:9000-9199"    # User range 6
    volumes:
      - ./proxy:/usr/local/etc/haproxy:rw
    networks:
      - minecraft_network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  minecraft_network:
    driver: bridge
