
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./mc_servers:/app/mc_servers
    ports:
      - "8000:8000"
      - "25565:25565"
    env_file:
      - .env
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "1105:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
