
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # Backend container exposes port range for Minecraft servers
    expose:
      - "25565-25700"  # Extended range for dynamic allocation
      - "11000-11999"  # Additional range for special servers (avoiding frontend port 1105)
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mc_servers:/app/mc_servers
      - ./proxy:/shared/proxy
    networks:
      - minecraft_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1105:1105"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - minecraft_network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "25565-25700:25565-25700"  # Extended range for dynamic allocation
      - "11000-11999:11000-11999"  # Additional range for special servers
      - "8404:8404"                # HAProxy stats interface
    volumes:
      - ./proxy:/usr/local/etc/haproxy:rw
    networks:
      - minecraft_network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mc_servers:
    driver: local

networks:
  minecraft_network:
    driver: bridge